version: "3.4"
services:
    app:
        container_name: node_server
        build: .
        restart: always
        env_file: .env
        ports:
           - "8000:3000"
        links:
           - mongo
    mongo:
        container_name: mongo
        image: mongo:3.4
        restart: always
        env_file: .env
        volumes: 
           - db-data:/data/db
        ports:
           - "27018:27017"
volumes: 
    db-data: